site_name: dictpress / Documentation
theme:
  name: material
  # custom_dir: "mkdocs-material/material"
  logo: "images/favicon.png"
  favicon: "images/favicon.png"
  language: "en"
  font:
    text: 'Inter'
    weights: 400
  direction: 'ltr'
  extra:
  search:
    language: 'en'
  features:
    - navigation.expand

  palette:
    primary: "white"
    accent: "#b78900"

site_dir: _out

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  - "static/style.css"

copyright: "Copyright &copy; 2022, Kailash Nadh."

nav:
  - "Introduction": index.md
  - "Installation": installation.md
  - "Data structure": data-structure.md
  - "Templates": templates.md
  - "Importing data": import.md
  - "Admin UI": admin.md
  - "Public APIs":
    - "Config": api/config.md
    - "Search": api/search.md
    - "Submissions": api/submissions.md
  - "Private APIs":
    - "Introduction": api/intro-private.md
    - "Entries": api/entries.md
    - "Relations": api/relations.md
